services:
  database:
    image: postgres:15
    container_name: gym-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gymdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gymdb"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  nextjs:
    build: .
    container_name: gym-app
    restart: always  
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy 
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/gymdb
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next